chore: allow /txs/count to be filtered by tx_type
aeternity/ae_mdw pull request #1008
Opened 2022-11-09 13:52 UTC by sborrazas

This change allows filtering txs count by both `type` and `tx_type` to avoid the request being blocked by browser tracker/ad blockers.

2022-11-09 15:45 UTC, thepiwo approved these changes

2022-11-09 15:48 UTC, thepiwo commented
@lukeromanowicz we will let you know when it is released

2022-11-09 21:47 UTC, jyeshe requested changes
Could you provide a test case?

2022-11-10 10:32 UTC, sborrazas commented
@jyeshe done

2022-11-10 11:20 UTC, merged