feat: track aex9 contract supplies
aeternity/ae_mdw pull request #1265
Opened 2023-04-12 15:56 UTC by jyeshe

Closes #1256

2023-04-12 16:10 UTC, sborrazas requested changes

2023-04-13 10:36 UTC, sborrazas approved these changes

2023-04-13 10:49 UTC, merged

2023-05-29 10:37 UTC, janmichek commented
I am not sure how this has been resolved.
Is it the `event_supply`? 
![image](https://github.com/aeternity/ae_mdw/assets/15363559/7240f772-46fb-401f-a51f-d925ac174ce9)

Could you provide some examples, please?

2023-06-26 07:59 UTC, jyeshe commented
> I am not sure how this has been resolved. Is it the `event_supply`? ![image](https://user-images.githubusercontent.com/15363559/241712322-7240f772-46fb-401f-a51f-d925ac174ce9.png)
> 
> Could you provide some examples, please? @jyeshe

@janmichek the `initial_supply` is set for the state of the contract right after its creation while the `event_supply` is updated after an event affecting the supply as `Mint`, `Burn` or `Swap`.

This is an old contract with `initial_supply` without respective `Mint` (it was not mandatory before):
https://mainnet.aeternity.io/mdw/v2/aex9/ct_ukZe6BBpuSWxT8hxd87z11vdgRnwKnedEWqJ7SyQucbX1C1pc

This is a contract with `event_supply` updated:
https://testnet.aeternity.io/mdw/v2/aex9/ct_Uzo1WEmzFYpdZsyyLMmkofZEKiiNiEnPaudvjHCpFCcourHch
corresponding to these events:
https://testnet.aeternity.io/mdw/v2/contracts/logs?contract=ct_Uzo1WEmzFYpdZsyyLMmkofZEKiiNiEnPaudvjHCpFCcourHch