perf: improve mem sync
aeternity/ae_mdw pull request #1461
Opened 2023-07-13 13:36 UTC by jyeshe

## What

Replace `GbTree` with ets based `SortedTable`.

## Why

refs #1389 + out of sync issue on mainnet on 5k+ contract calls

## Notes

Benchmark result for 10k contract calls with 2 event logs each:
```
root@3e66f18de36a:/app# MIX_ENV=test elixir -S mix run --no-start test/support/bench/sorted_table.exs 

Operating System: Linux
CPU Information: AMD Ryzen 7 5800H with Radeon Graphics
Number of Available Cores: 16
Available memory: 15.48 GB
Elixir 1.13.4
Erlang 23.3.4.18

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 14 s

Benchmarking GbTree...
Benchmarking SortedTable...

Name                  ips        average  deviation         median         99th %
SortedTable         12.77    0.00130 min     ±5.58%    0.00131 min    0.00149 min
GbTree             0.0148       1.13 min     ±0.00%       1.13 min       1.13 min

Comparison: 
SortedTable         12.77
GbTree             0.0148 - 863.34x slower +1.13 min
```

2023-07-14 15:23 UTC, sborrazas requested changes
Just a few things, but the rest looks great!

2023-07-17 07:09 UTC, jyeshe commented on lib/ae_mdw/sync/mem_store_creator.ex
> +      Enum.split_with(prev_stores, fn %{time: time} ->
It needs to pick the old ones that are at the end of the list. I could still use `drop_while` but within 2 minutes only a max of 40 stores can be created or 120 on hyperchains with 1s finality.

2023-07-17 07:46 UTC, jyeshe commented on lib/ae_mdw/db/mem_store.ex
> +    count_db + count_mem
Thanks and added a check to see if it's a new key. If it is not we don't increment the counting and only decrement if it's a per-existing key.

2023-07-17 10:10 UTC, sborrazas commented on lib/ae_mdw/sync/mem_store_creator.ex
> +      Enum.split_with(prev_stores, fn %{time: time} ->
Can we change this function anyway to avoid having to do the math or change this function if the amount of stores changes in the future?

2023-07-17 14:44 UTC, jyeshe commented on lib/ae_mdw/sync/mem_store_creator.ex
> +      Enum.split_with(prev_stores, fn %{time: time} ->
Good point, there was an alternative to release it based on commits.

2023-07-17 18:13 UTC, sborrazas approved these changes

2023-07-17 18:35 UTC, merged