chore: remove further unused v1 routes
aeternity/ae_mdw pull request #1962
Opened 2024-10-07 13:32 UTC by sborrazas

2024-10-07 13:39 UTC, yaboiishere requested changes

2024-10-07 13:39 UTC, yaboiishere commented on test/ae_mdw_web/controllers/name_controller_test.exs
Here you're removing some fo the v3 tests too

2024-10-08 10:49 UTC, sborrazas commented on test/ae_mdw_web/controllers/name_controller_test.exs
Hadn't realized I had removed v3 endpoint tests too, thanks 👍

2024-10-08 11:52 UTC, yaboiishere approved these changes

2024-10-15 11:07 UTC, merged