fix: transactions for account listing
aeternity/ae_mdw pull request #1993
Opened 2024-10-23 12:16 UTC by vatanasov

2024-10-24 07:57 UTC, yaboiishere approved these changes

2024-10-24 11:24 UTC, sborrazas requested changes

2024-10-24 11:24 UTC, sborrazas commented on lib/ae_mdw/fields.ex
> +    end
Can we use an `if` expression here instead?

2024-10-29 10:39 UTC, sborrazas approved these changes

2024-10-29 10:39 UTC, merged