feat: add gas to microblocks
aeternity/ae_mdw pull request #2023
Opened 2024-11-21 14:24 UTC by yaboiishere

resolves: #2019

2024-11-25 08:10 UTC, vatanasov approved these changes

2024-11-25 10:36 UTC, sborrazas requested changes

2024-11-25 10:36 UTC, sborrazas commented on lib/ae_mdw/blocks.ex
> +    gas = mb_hash |> :aec_db.get_block() |> :aec_blocks.gas()
Can we instead fetch the block and then get the header from it? That way we avoid fetching it twice
```elixir
block = :aec_db.get_block(mb_hash)
header = :aec_blocks.to_header(block)
gas = :aec_blocks.gas(block)
```

2024-11-26 12:52 UTC, sborrazas approved these changes

2024-11-26 12:52 UTC, merged