test: update NameController tests to be unit tests
aeternity/ae_mdw pull request #235
Opened 2021-09-02 15:28 UTC by sborrazas

Didn't need to use `with_blockchain/2` because the NameController exclusively depends on the mdw database.

2021-09-02 17:59 UTC, jyeshe reviewed
Could we keep the not mocked ones or add integration tests for the protocol please? For those not passing that are hard to fix we could `@skip` them. 
IMHO the controller tests could be mocked, to focus testing on input and output (parameter validation and formating response) but before that it would be good to have protocol unit tests as integration tests. In short, protocol real tests, controller mocked ones.

2021-09-02 18:12 UTC, sborrazas commented
@jyeshe I'm assuming by protocol you mean `AeMdw.*` modules, right? If that's the case then I agree, we should have tests for those. These should actually hit mnesia records that are inserted before the test runs, so they still shouldn't depend on a synced blockchain.

I think a lot of simplification can be done while creating unit tests under the middleware library (`AeMdw.*`). Meanwhile, we should probably keep mocking tests under the web modules (`AeMdwWeb.*`) like this PR does. Creating tests under `AeMdw.*` will probably take a couple of months.

2021-09-03 09:17 UTC, jyeshe commented
> @jyeshe I'm assuming by protocol you mean `AeMdw.*` modules, right? If that's the case then I agree, we should have tests for those. These should actually hit mnesia records that are inserted before the test runs, so they still shouldn't depend on a synced blockchain.
> 
> I think a lot of simplification can be done while creating unit tests under the middleware library (`AeMdw.*`). Meanwhile, we should probably keep mocking tests under the web modules (`AeMdwWeb.*`) like this PR does. Creating tests under `AeMdw.*` will probably take a couple of months.

Sorry, by protocol I mean chain, info that comes and goes from/to the chain nodes. 
I agree about the unit tests so we could leave the integration tests, as they are validating the interaction with the chain, and add new mocked tests to increase the coverage of unit tests.

2021-09-06 09:31 UTC, thepiwo commented
@Artur64 can you review this?

2021-09-07 13:41 UTC, jyeshe approved these changes

2021-09-13 18:17 UTC, jyeshe requested changes
Could we keep the integration as they are and add unit tests?

2021-09-14 12:40 UTC, sborrazas commented
@jyeshe for some reason I changed the integration test instead of adding it to the unit `name_controller_test`. It's fixed now!

2021-09-14 14:05 UTC, jyeshe approved these changes
Tests passed

2021-09-14 15:53 UTC, thepiwo approved these changes

2021-09-14 21:41 UTC, merged