fix: account presence based on aex9 balance
aeternity/ae_mdw pull request #262
Opened 2021-09-29 21:07 UTC by jyeshe

## Additional Notes

These are the aex9 contracts for which a call to get their store/balance returns "Out of gas" error:

Out of gas for ct_2M4mVQCDVxu6mvUrEue1xMafLsoA1bgsfC3uT95F3r1xysaCvE
Out of gas for ct_21oSi6uMMcnnyxc1KTP8MReBPVvBQQ9oeoA7aexQBsF2o16HwT
Out of gas for ct_2czjMpbeeds9Geb272UfiEvhQHc8QZM5AM8jngwpqdMnWNDP3h
Out of gas for ct_25JPViJPDPjroiL1wr1ngWJ8pK5ykN7x3LqGMWPCuC6PtLjzKT
Out of gas for ct_2mzKUzT55wz4wYUmH4s3dHf3YBprDLi92uxvEah8fe3BaLfkBU
Out of gas for ct_2bFV4kxtmUeKTF5Eb5STfnAx6UgxzBqTL1pYLF1GBhcmoQAhLf
Out of gas for ct_BmCPDh6TK3KtWdwKEJrSCnrvghbkjekuTTh7B5tLGduF6rTFG
Out of gas for ct_227nuD7YiHL7pJ63FP1CnbhKgU9ueWKP77sA26huE47s31tuqQ
Out of gas for ct_jyw2fRpr6srNwSqE6FJFyZSD1upD91eZ5ZZKZfBhuDmBxTU53
Out of gas for ct_VxFemyM2ML15ApWrFqBKrarVbNfBASPBs1SC1zMuwaWrnrTSy
Out of gas for ct_2GPhKGbRxZaaJtqRTnxLk5UDSNNEtRt3tyWuKVQeoVrerRfhHa
Out of gas for ct_7UfopTwsRuLGFEcsScbYgQ6YnySXuyMxQWhw6fjycnzS5Nyzq
Out of gas for ct_M9yohHgcLjhpp1Z8SaA1UTmRMQzR4FWjJHajGga8KBoZTEPwC
Out of gas for ct_BwJcRRa7jTAvkpzc2D16tJzHMGCJurtJMUBtyyfGi2QjPuMVv
Out of gas for ct_2nTgwxN75pFeFJxjNfohVJHZg4p3tth4f8hhVpxbdNHPdoEMHp
Out of gas for ct_uGk1rkSdccPKXLzS259vdrJGTWAY9sfgVYspv6QYomxvWZWBM
Out of gas for ct_26GAggwrHJLw45vopxu1HA51t6pw4xjzqvq66kh1WPtZjNXMyL

2021-09-30 17:37 UTC, jyeshe commented on lib/ae_mdw_web/controllers/aex9_controller.ex
> -  defp normalize_balances(bals) do
moved to lib/ae_mdw_web/helpers/aex9_helper.ex

2021-09-30 17:37 UTC, jyeshe commented on lib/ae_mdw_web/controllers/aex9_controller.ex
> -  defp balance_to_map({amount, txi, contract_pk}) do
moved to lib/ae_mdw_web/views/aex9_view.ex

2021-09-30 17:37 UTC, jyeshe commented on lib/ae_mdw_web/controllers/aex9_controller.ex
> -  defp transfer_to_map({recipient_pk, sender_pk, amount, call_txi, log_idx}, :rev_aex9_transfer),
moved to lib/ae_mdw_web/views/aex9_view.ex

2021-09-30 19:09 UTC, sborrazas requested changes
Looks good, just some minor adjustments perhaps?

2021-10-01 07:21 UTC, thepiwo commented
Do we have some idea on the performance hit of these changes?

2021-10-01 09:07 UTC, jyeshe commented
> Do we have some idea on the performance hit of these changes?

It's quite slow. The sync process logic works sequentially but well reminded, this specific part we might probably run in parallel. Thanks

2021-10-01 14:47 UTC, sborrazas approved these changes

2021-10-01 16:13 UTC, thepiwo approved these changes

2021-10-01 16:57 UTC, merged