refactor: add paginated txs endpoint
aeternity/ae_mdw pull request #283
Opened 2021-10-11 19:32 UTC by sborrazas

2021-10-12 16:31 UTC, jyeshe reviewed
Still reviewing but since it's a complex task we could add new tests comparing new and old responses, specially for /txs/:direction endpoints.

2021-10-13 09:48 UTC, jyeshe requested changes
I understand this is the idiom of current implementation, with (powerful) high order functions receiving more than 1 function as parameter. However I would rather go, if possible, with iterations on a pipe like: 
fetch_after_cursor 
|> filter 
|> sort
where fetch_after_cursor fetches some amount with minimum criteria (txi > some_txi).

I know this is though, when you have a big code and someone suggests a refactoring. Once this is an improvement feature (the general refactoring the pagination), we could discuss ways to reduce the complexity of these functions.

I think a good starting point would be the refactoring suggested on `AeMdw.Txs.render_list/2` as simplifying the `table_keys` will help to simplify the output of `AeMdw.Collection.merge_with_keys/3` and maybe reduce the complexity on the way back to its processing.

2021-10-13 09:48 UTC, jyeshe commented on lib/ae_mdw/txs.ex
> +  #        - Same thing for oracle_query_tx fields
nice filtering order

2021-10-13 09:48 UTC, jyeshe commented on lib/ae_mdw/txs.ex
> +    end)
table_keys could be contain only `txi` as the tables are not used.

2021-10-14 09:03 UTC, jyeshe commented on lib/ae_mdw/txs.ex
> +  end
It is missing in the HEAD.

2021-10-14 09:04 UTC, jyeshe commented on test/integration/ae_mdw_web/controllers/tx_controller_test.exs
> +      assert ^data = response["data"]
thank you

2021-10-14 13:18 UTC, sborrazas commented on lib/ae_mdw/collection.ex
> +  @spec stream(table(), direction(), cursor()) :: Enumerable.t()
It was cursor(), I renamed the parameter to be cursor instead

2021-10-18 10:20 UTC, jyeshe commented on lib/ae_mdw/txs.ex
> +        end
sorry, clarifying the 3 extract functions actually would be only 1 function with 4 different params. This way we cloud replace the deep nesting with pattern matching:
```
defp extract_transaction_by([]), do: []

defp extract_transaction_by([type]) when type in ~w(account contract channel oracle name) do
  tx_types =
    if type == "account" do
      Node.tx_types()
    else
      Node.tx_group(String.to_existing_atom(type))
    end

  Enum.flat_map(tx_types, fn tx_type ->
    poss = tx_type |> Node.tx_ids() |> Map.values() |> Enum.map(&{tx_type, &1})
    # nil - for link
    if tx_type in @create_tx_types, do: [{tx_type, nil} | poss], else: poss
  end)
end

defp extract_transaction_by([field]) do
...
end

defp extract_transaction_by([type, field]) do
...
end
```

2021-10-19 07:29 UTC, jyeshe reviewed
```
1) test txs_direction with given type and type_group parameters get transactions when direction=backward, type=oracle_register and type_group=spend with default limit (Integration.AeMdwWeb.TxControllerTest)
     test/integration/ae_mdw_web/controllers/tx_controller_test.exs:732
     match (=) failed
     The following variables were pinned:
       data = [%{"block_hash" => "mh_2ViLVHZpmHibA4aqrUZ59hvy52mntJFG28MWMRgnGDPwR5ZicJ", "block_height" => 502638, "hash" => "th_2UQ9p7KzXRKKLsRDW1RMRdZRuKVPw6RbeftDDko6ZLdXCHxT3d", "micro_index" => 36, "micro_time" => 1634483021732, "signatures" => ["sg_YHDBZgtrhWgYCwe964z4AnH4ZxhbE4zE2JmARnyJhgJdTPLCM9wsALS23syUrYr5Eb9Qtc3kft3f4txDaTPWsJfCvARdn"], "tx" => %{"amount" => 20000, "fee" => 19320000000000, "nonce" => 5978553, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oX2RTUThteFl4eWtKRWhMRjZNMXlzVTRSTDlibnlKck5DZmRIbXZRVTdmUjVZRUVOdjY6MTYzNDQ4MzAyM0vBSb4=", "recipient_id" => "ak_2QkttUgEyPixKzqXkJ4LX7ugbRjwCDWPBT4p4M2r8brjxUxUYd", "sender_id" => "ak_2QkttUgEyPixKzqXkJ4LX7ugbRjwCDWPBT4p4M2r8brjxUxUYd", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065127}, %{"block_hash" => "mh_dSQ8mxYxykJEhLF6M1ysU4RL9bnyJrNCfdHmvQU7fR5YEENv6", "block_height" => 502638, "hash" => "th_uvVaozAW4uHeVwdtczfNrqmtGsNrS3RUKE1LdtDSJ8hBV4zaF", "micro_index" => 35, "micro_time" => 1634483017672, "signatures" => ["sg_BFZYYXiVDxsKGHwc9ENx7E5kDvGYu4sVm4cABKoPY9iuPhKKaDtafEsmEn4ARxKsixNeskqbx7sSLTL3v5GpXAVFhMSGy"], "tx" => %{"amount" => 20000, "fee" => 19340000000000, "nonce" => 5535416, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oXzJRYlh1ckVOdDNmOTdZQ3hNSEZFUkQ5UW44QXI1ZXdDOTZ4V21WOHJKY1hmbkpKazU2OjE2MzQ0ODMwMjGdlGeT", "recipient_id" => "ak_KHfXhF2J6VBt3sUgFygdbpEkWi6AKBkr9jNKUCHbpwwagzHUs", "sender_id" => "ak_KHfXhF2J6VBt3sUgFygdbpEkWi6AKBkr9jNKUCHbpwwagzHUs", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065126}, %{"block_hash" => "mh_2QbXurENt3f97YCxMHFERD9Qn8Ar5ewC96xWmV8rJcXfnJJk56", "block_height" => 502638, "hash" => "th_2848j6a4cRTMouruotgDkLb53hpYhpxx9VYyzmhx3qdGyjRqRB", "micro_index" => 34, "micro_time" => 1634483014672, "signatures" => ["sg_CErwi9AKVMP59JSCBZq9CcUXSyZqUx1cXf2w1oJ9zGKxcPJpCQKdtC4w6jp1wvUv4YwZLYzwRRQQ6vWSEkzKVSzJdfvV4"], "tx" => %{"amount" => 20000, "fee" => 19320000000000, "nonce" => 5785483, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oX2JKQXFkcE1jaTlReFhIdUZYOWdzMURIck5vWGlwalZ5OXVmUmRIdmM1OFlMdURNQmg6MTYzNDQ4MzAxNuQQjqY=", "recipient_id" => "ak_zvU8YQLagjcfng7Tg8yCdiZ1rpiWNp1PBn3vtUs44utSvbJVR", "sender_id" => "ak_zvU8YQLagjcfng7Tg8yCdiZ1rpiWNp1PBn3vtUs44utSvbJVR", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065125}, %{"block_hash" => "mh_bJAqdpMci9QxXHuFX9gs1DHrNoXipjVy9ufRdHvc58YLuDMBh", "block_height" => 502638, "hash" => "th_YCiMu8TdnDMJZ62jJEnMSAt8EqxCrkWSsLGc7zoPod9VATM8i", "micro_index" => 33, "micro_time" => 1634483011627, "signatures" => ["sg_BL5L7SXzg3Bjm2xTYgHRr19BbXq1S7aeVQxpcTeTJAaXSQ7FzV5DYTLRzNT1zVJq1Z887t14MsJsQXELbC8WfYfTTLKbB"], "tx" => %{"amount" => 20000, "fee" => 19320000000000, "nonce" => 5998644, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oX1MxSGRmajdzWHlhSGNkYXhLRzU5NjN1WHpBeUxadFdtWGU3RWRwZGtmMkU1WGs4WWI6MTYzNDQ4MzAxNC9bBnM=", "recipient_id" => "ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq", "sender_id" => "ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065124}, %{"block_hash" => "mh_bJAqdpMci9QxXHuFX9gs1DHrNoXipjVy9ufRdHvc58YLuDMBh", "block_height" => 502638, "hash" => "th_2WsXwhMPAphZ9Agz2GNJBmsh6s6EyiKQRQimWEVxUUzYvWHQrM", "micro_index" => 33, "micro_time" => 1634483011627, "signatures" => ["sg_Uvu84dbPYJijMrRCedRa7TNEo2mMFnh1ckeJosdMQajdxQN2sj8t4d95hR2SBx1ck8BRNBeztZGC9PpySze5AE6GzCexY"], "tx" => %{"amount" => 20000, "fee" => 19320000000000, "nonce" => 5978552, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oX1MxSGRmajdzWHlhSGNkYXhLRzU5NjN1WHpBeUxadFdtWGU3RWRwZGtmMkU1WGs4WWI6MTYzNDQ4MzAxM6SPlRQ=", "recipient_id" => "ak_2QkttUgEyPixKzqXkJ4LX7ugbRjwCDWPBT4p4M2r8brjxUxUYd", "sender_id" => "ak_2QkttUgEyPixKzqXkJ4LX7ugbRjwCDWPBT4p4M2r8brjxUxUYd", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065123}, %{"block_hash" => "mh_S1Hdfj7sXyaHcdaxKG5963uXzAyLZtWmXe7Edpdkf2E5Xk8Yb", "block_height" => 502638, "hash" => "th_2UdHkMc6qi6Tjcxs2ks1ahXoEXq8dgb6uKR1DjPEWN8bmDeF1m", "micro_index" => 32, "micro_time" => 1634483007940, "signatures" => ["sg_XGvApVS6Pza6Au8LwYhScmVpgjtSzTzkoiWfvC6jUgx2iccaNwCLqanKmn2Zw3FU5XrpZ4D5VaqsDSutLoaKuXg1Ct9X1"], "tx" => %{"amount" => 20000, "fee" => 19340000000000, "nonce" => 5535415, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oXzJ2cFc4Mm0yWk1YcXRDeXNDVjJvc0htcVl6WW43S1JFN3FleXpGV2M1aG9RUjdncFRrOjE2MzQ0ODMwMTGmlB7p", "recipient_id" => "ak_KHfXhF2J6VBt3sUgFygdbpEkWi6AKBkr9jNKUCHbpwwagzHUs", "sender_id" => "ak_KHfXhF2J6VBt3sUgFygdbpEkWi6AKBkr9jNKUCHbpwwagzHUs", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065122}, %{"block_hash" => "mh_2vpW82m2ZMXqtCysCV2osHmqYzYn7KRE7qeyzFWc5hoQR7gpTk", "block_height" => 502638, "hash" => "th_aQjdfsViMNCEUWx1rRfN2MZNgE5uoKw6G9vX54Si3uupaNF6r", "micro_index" => 31, "micro_time" => 1634483004878, "signatures" => ["sg_R97F53CBZ6rseeXHoc4cCZnDnKrU2X72KBrfbW58dwocNAhD7PDiE66tBqJjsmzwvFjARnkcyqDEM4sF185mepizYKvsC"], "tx" => %{"amount" => 20000, "fee" => 19340000000000, "nonce" => 5785482, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oXzJETUxuYXlqSERmdzZxS0xUMW80RDVLRjFhemI0S2l4TU1uZEJlcEZ1a0NOYjZiZjh6OjE2MzQ0ODMwMDYT19Gl", "recipient_id" => "ak_zvU8YQLagjcfng7Tg8yCdiZ1rpiWNp1PBn3vtUs44utSvbJVR", "sender_id" => "ak_zvU8YQLagjcfng7Tg8yCdiZ1rpiWNp1PBn3vtUs44utSvbJVR", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065121}, %{"block_hash" => "mh_2DMLnayjHDfw6qKLT1o4D5KF1azb4KixMMndBepFukCNb6bf8z", "block_height" => 502638, "hash" => "th_tCjNsfWSMcaeDHHhsqrSAj2L5vtRMZENtAP1cERTpupLaFSrQ", "micro_index" => 30, "micro_time" => 1634483001848, "signatures" => ["sg_J1bdZ9jomaLuJW8XrCJ9J2u5L2NWEdmhJiwKQXcp8vnbg79t1MirZdVk8QrXxjQysVj7NJsak3wHbvLFjE6hVEPvf8a3E"], "tx" => %{"amount" => 20000, "fee" => 19320000000000, "nonce" => 5998643, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oX3ZYSnhlRmVkZ1BtNHZhZ25TNENjWUcxUWJNRUxIb29KbkVURHdMRWlZNXBnVXkzZGk6MTYzNDQ4MzAwNCUSfIM=", "recipient_id" => "ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq", "sender_id" => "ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065120}, %{"block_hash" => "mh_2DMLnayjHDfw6qKLT1o4D5KF1azb4KixMMndBepFukCNb6bf8z", "block_height" => 502638, "hash" => "th_25XebYxqxzE9vSK2uw2oaWeMNFfU2yH4Z9QKFJt3Q9AZZ81cin", "micro_index" => 30, "micro_time" => 1634483001848, "signatures" => ["sg_HSLLqDhdDnVzZwRBsgMb4FwKRqkUdpFVe6NXBfGwFebReF8iXnw59P92odJRPTQP5iPdPW8kzSbJhbFKtyXi4qUpxUZMz"], "tx" => %{"amount" => 20000, "fee" => 19320000000000, "nonce" => 5978551, "payload" => "ba_NTAyNjM4OmtoXzJNZURqTWdlTTRCVEhiS3dxVG93VGVXNWtodFdFaVB4cGR4QmpwdnFKdHhiemNGUW5xOm1oX3ZYSnhlRmVkZ1BtNHZhZ25TNENjWUcxUWJNRUxIb29KbkVURHdMRWlZNXBnVXkzZGk6MTYzNDQ4MzAwM7UTwcY=", "recipient_id" => "ak_2QkttUgEyPixKzqXkJ4LX7ugbRjwCDWPBT4p4M2r8brjxUxUYd", "sender_id" => "ak_2QkttUgEyPixKzqXkJ4LX7ugbRjwCDWPBT4p4M2r8brjxUxUYd", "ttl" => 502648, "type" => "SpendTx", "version" => 1}, "tx_index" => 27065119}, %{"block_hash" => "mh_vXJxeFedgPm4vagnS4CcYG1QbMELHooJnETDwLEiY5pgUy3di", "block_height" => 502638, "hash" => "th_2CYLsajcNfGomnyhTsYVEs6jvUWrAy77qRi1nup9RjZ9JUQeVW", "micro_index [...]

2021-10-19 12:34 UTC, sborrazas commented
@jyeshe I get none of those errors. Do you have the mdw fully synced?

2021-10-20 10:59 UTC, merged