feat: add cursor-based pagination to contract logs/calls
aeternity/ae_mdw pull request #392
Opened 2021-12-13 01:57 UTC by sborrazas

2021-12-13 01:58 UTC, sborrazas commented
Requires #391 to be merged first

2021-12-13 12:29 UTC, thepiwo approved these changes

2021-12-13 15:51 UTC, jyeshe requested changes
Code looks good but safer to be validated (and continue to work without regression) with unit tests for the module `AeMdw.Contracts`.

2021-12-16 09:23 UTC, jyeshe approved these changes

2021-12-16 11:20 UTC, merged