test: restructure oracles integration tests
aeternity/ae_mdw pull request #423
Opened 2021-12-24 15:13 UTC by sborrazas

The purpose of this is to test pagination properly, with the added
benefit that many of the tests would fail when there's name
inconsistencies.

Requires #421 to be merged first.

2021-12-27 11:06 UTC, thepiwo approved these changes

2022-01-03 20:25 UTC, jyeshe requested changes
Is there any failing right now for you? If so could you comment which ones and why they fail please?

2022-01-05 10:32 UTC, sborrazas commented
@jyeshe no failures on oracles. Only still getting failures on names.

2022-01-06 14:07 UTC, jyeshe approved these changes
all tests passed

2022-01-06 14:37 UTC, merged