refactor: extract channel_create_tx syncing to Sync.Transaction
aeternity/ae_mdw pull request #429
Opened 2021-12-30 16:45 UTC by sborrazas

Requires #428 to be merged

2021-12-30 16:49 UTC, thepiwo approved these changes

2022-01-03 16:21 UTC, jyeshe requested changes

2022-01-03 16:21 UTC, jyeshe commented on lib/ae_mdw/db/sync/transaction.ex
> +         signed_tx,
This param is only used by `:channel_create_tx`(and no other tx will use it). Could we move it outside of `tx_mutations` too? (following same reasoning as https://github.com/aeternity/ae_mdw/pull/426#discussion_r777557249)

2022-01-03 20:17 UTC, jyeshe approved these changes
The `signed_tx` param is only used by `:channel_create_tx` (and no other tx will use it). 
Since this is crossing 3 PRs and it's a design issue that is more subject, from my side I leave it optional request for now or later.

2022-01-05 19:16 UTC, merged