feat: add prev link cursor on paginated endpoints
aeternity/ae_mdw pull request #526
Opened 2022-02-10 16:49 UTC by sborrazas

2022-02-10 19:34 UTC, jyeshe requested changes
I like the general idea and the integration tests looks trustworthy.

There are some issues with opportunity for higher coverage:
1. http://localhost:4000/txs/forward
then go to next
http://localhost:4000/txs/forward?cursor=10
then go to prev
/txs/forward?cursor=9&rev=1 
gives  `error: "invalid id: 1"`
2. `prev` could be nil for all paths on first hit without cursor likewise `/blocks/forward`
3. similar cases to 1. are (possibly not be limited to)
http://localhost:4000/contracts/calls/forward
http://localhost:4000/contracts/logs/forward

2022-02-10 19:34 UTC, jyeshe commented on lib/ae_mdw/collection.ex
> +    # IO.inspect(["PAGINATION", p, res])
nit pick for merging

2022-02-10 19:34 UTC, jyeshe commented on lib/ae_mdw_web/controllers/block_controller.ex
> +    paginate(conn, prev_cursor, blocks, next_cursor)
:100:

2022-02-11 14:07 UTC, thepiwo reviewed
we should probably document that in the readme?

2022-02-11 14:57 UTC, jyeshe reviewed
Code looks good to me and `/txs/forward` going next and prev works.
Missing only the same `invalid rev` fix for:
http://localhost:4000/contracts/calls/forward
http://localhost:4000/contracts/logs/forward

2022-02-11 16:21 UTC, sborrazas commented
@jyeshe done, thanks

2022-02-11 16:21 UTC, sborrazas commented
> we should probably document that in the readme?

I've now updated the README to include the `prev` parameter in the instructions. Thanks for reminding me!

2022-02-11 16:30 UTC, jyeshe approved these changes

2022-02-11 17:45 UTC, merged