refactor: remove and make private unused modules/functions
aeternity/ae_mdw pull request #527
Opened 2022-02-11 20:13 UTC by sborrazas

2022-02-13 21:51 UTC, thepiwo approved these changes

2022-02-14 13:50 UTC, jyeshe requested changes
Nice initiative. To complete the removal, the `AeMdwWeb.NameController.search` is asking for another implementation:
```
Compiling 134 files (.ex)
warning: AeMdw.Db.Stream.Name.auction_prefix_resource/3 is undefined (module AeMdw.Db.Stream.Name is not available or is yet to be defined)
  lib/ae_mdw_web/controllers/name_controller.ex:274: AeMdwWeb.NameController.prefix_stream/3

warning: AeMdw.Db.Stream.Name.prefix_resource/4 is undefined (module AeMdw.Db.Stream.Name is not available or is yet to be defined)
Found at 2 locations:
  lib/ae_mdw_web/controllers/name_controller.ex:282: AeMdwWeb.NameController.prefix_stream/3
  lib/ae_mdw_web/controllers/name_controller.ex:291: AeMdwWeb.NameController.prefix_stream/3
```

2022-02-14 14:34 UTC, sborrazas commented
@jyeshe we have compilation "warnings as errors" option enabled, but apparently these kinds of warnings don't cause compilation errors. From what I've seen on the elixir repo we need to update the Elixir version for that to happen. Thanks for catching it!

2022-02-14 14:58 UTC, jyeshe approved these changes

2022-02-14 15:11 UTC, merged