fix: fix usage of Collection.stream for getting int calls
aeternity/ae_mdw pull request #605
Opened 2022-03-26 16:01 UTC by sborrazas

Problem was the Collection.stream/4 exepcts the scope to always be
{first, last}, regardless of the direction.

Refs #604

2022-03-27 10:37 UTC, thepiwo approved these changes

2022-03-28 08:15 UTC, jyeshe requested changes
This fix replacing Collection.stream/4 by Collection.stream/2 had been done here: https://github.com/aeternity/ae_mdw/pull/594/commits/3107d95286514fd433a0b8bfa2837f53e526d91d (before reporting the issue, needed to pass 7 integration tests)

We can wait for a fix for the `Collection.stream/4` instead (we could have a validation depending on the direction).

2022-03-28 09:55 UTC, sborrazas commented
@jyeshe `Collection.stream/4` wasn't broken, it was incorrectly used because the scope sent was `{last, first}` instead of `{first, last}` which is the correct way of using it

2022-03-28 10:02 UTC, jyeshe commented
> @jyeshe `Collection.stream/4` wasn't broken, it was incorrectly used because the scope sent was `{last, first}` instead of `{first, last}` which is the correct way of using it

I see, I think `Collection.stream/4` should have a validation when the direction is `backward` and the expected first < last is not met.

2022-03-28 10:04 UTC, jyeshe commented
This will help us until detecting silent errors until we improve the test coverage.

2022-03-28 10:17 UTC, sborrazas commented
Fixed on https://github.com/aeternity/ae_mdw/commit/3107d95286514fd433a0b8bfa2837f53e526d91d

2022-03-28 10:17 UTC, closed without merging